language: python
python: 2.7
sudo: required
dist: bionic
arch: arm64
env:
  global:
    - ARCH=${TRAVIS_ARCH}
    - TAG=${TAG:-latest}
    - DISTRO=centos
    - VERSION=7

services:
  - docker

script:
  # Run container in detached state
  - env
  - sudo docker pull arm64v8/centos:7
  - docker login -u "$DOCKERHUBUSER" -p "$DOCKERHUBPSW"
  - sudo docker run -di --name ovs_agent_docker -v $(pwd):/neutron-openvswitch-agent-builder -v /var/run/docker.sock:/var/run/docker.sock arm64v8/centos:7 /usr/sbin/init
  - sudo docker exec -i ovs_agent_docker uname -a
  - sudo docker exec -i ovs_agent_docker cat /etc/redhat-release

# Install prereqs
  - sudo docker exec -i ovs_agent_docker bash -cx 'curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python2 ./get-pip.py'
  - sudo docker exec -i ovs_agent_docker bash -cx 'pip install setuptools tox pbr jinja2'
  - sudo docker exec -i ovs_agent_docker bash -cx "yum install -y git"

# Install Kolla
  - git clone https://github.com/openstack/tripleo-repos $(pwd)/tripleo-repos
  - sudo docker exec -i ovs_agent_docker bash -cx 'cd /neutron-openvswitch-agent-builder/tripleo-repos; python2 ./setup.py install'

  - git clone https://github.com/openstack/kolla $(pwd)/kolla
  - sudo docker exec -i ovs_agent_docker bash -cx 'cd /neutron-openvswitch-agent-builder/kolla; pip install -r requirements.txt; python2 ./setup.py install'

# Create Docker
  - sudo docker exec -i ovs_agent_docker kolla-build --base ${DISTRO} --base-arch ${ARCH} neutron-openvswitch-agent

# Upload docker
  - docker_uuid=$(docker images|grep binary-neutron-openvswitch-agent|awk '{print $3}')
  - docker_version=$(docker images|grep binary-neutron-openvswitch-agent|awk '{print $2}')

  - docker tag $docker_uuid mellanox/${DISTRO}-binary-neutron-openvswitch-agent-${ARCH}:$docker_version
  - docker images
  - docker push mellanox/${DISTRO}-binary-neutron-openvswitch-agent-${ARCH}
